### ISSUE TITLE
Responsive Not Working

### ISSUE THREAD

**Issue by nzifnab** [jcblw/zoomy-plugin#15] opened 2013-09-27 00:10 UTC
I'm using zoomy here: http://thepointsaranac.com/overview

It works great at the larger window size, but when you decrease the window width to the responsive breakpoint and the image shrinks, zoomy goes all funky.  It's especially problematic when you refresh the page at that size to let zoomy re-initialize and then the image offset for the magnifying glass is COMPLETELY off.

Two questions I guess:

1) How can I make zoomy re-init when the responsive breakpoint is hit so that it doesn't let you use the magnifying glass way out-of-bounds, and 

2) Why is the offset so wrong when the image gets smaller and you refresh the page?

Edit:  wrong url.

**Comment by jcblw** [comment] 2013-10-20 18:49
duplicate of #14, please reference there for updates

**Closed as completed** 2013-10-20 18:50 UTC
